### ISSUE TITLE
Connection not possible if a client and Calimero Server on same Docker host

### ISSUE THREAD

**Issue by aschamberger** [calimero-project/calimero-server#12]
I tried running Calimero as planned on my production home assistant server. However its not working.
I already opened a issue at https://github.com/XKNX/xknx/issues/815 for the Home Assistant part.
However it seems the problem lies on the Calimero side if the client application is running on the same Docker host. When I run Calimero in the same setup on another device at least Routing works. Tunneling also fails.
You can find all the logs at https://github.com/XKNX/xknx/issues/815

**Comment by bmalinowsky** [comment]
Can you create a trace of what messages are actually going back and forth when you open a connection. Since you use containers, e.g., use netshoot alongside the server container:

docker run -it --rm --net container:<calimero container name> nicolaka/netshoot tcpdump

**Comment by aschamberger** [comment]
I'll send you the tcpdump of a home assisstant restart which hopefully includes the connect problems.
I did't want to publicly upload the tcpdump as it might include passwords as the all containers run in host networking mode.
Thanks for your support.

**Comment by farmio** [comment]
Hi 👋! 
I did try this too and ran into similar problems. Unfortunately I have no experience whatsoever with Java so debugging this is quite hard for me.
I have set up calimero docker server with port forwarding (`network_mode: "host"` didn't work properly on macOS) 
```xml
<knxServer name="calimero-server" friendlyName="Calimero KNX IP Server">
	<!-- KNXnet/IP search & discovery -->
	<discovery listenNetIf="all" outgoingNetIf="all" activate="true" />

	<!-- Provides the KNXnet/IP-side configuration for access to one KNX subnet -->
	<serviceContainer activate="true" routing="true" networkMonitoring="true" 
		udpPort="3671" listenNetIf="any">
		<knxAddress type="individual">7.1.0</knxAddress>
		<routing/>
```
and `<knxSubnet type="virtual">virtual-subnet</knxSubnet>` and tried establish a tunneling connection to it form `xknx`. The `ConnectionRequest` was never answered but it seems calimero has received it:
```java

calimero  | [calimero-server control endpoint virtual-subnet] INFO calimero.server.calimero-server - virtual-subnet: setup data endpoint (channel 1) for connection request from 127.0.0.1:50756 (udp)
calimero  | [calimero-server control endpoint virtual-subnet] INFO calimero.server.calimero-server - assign additional individual address 7.1.10 to channel 1
```
Is there a way to enable some kind of debug logging for the calimero conatiner?
Is it even possible to tunnel to a calimero server? Do I have to configure it somehow - I didn't find anything in the readme.

**Comment by bmalinowsky** [comment]
@farmio  Hi,
Docker on MacOS runs in a VM, so host networking won't work as you'd expect it to. With port forwarding, I can't remember right now how that reacts if you open a tunneling connection, as the communication ports change after connection setup (unless the server only supports 1 connection).

In the config file, for a container I would set `listenNetIf` to something more specific, "any" is basically if you know that the chosen netif is the one you want without needing its name.

Debug: well, yeah there is, but one of the first things I did after the 2.5 release was to make that easier, because it was quite cumbersome to change in a container that you throw away. It's not on Docker hub yet.

Tunneling is always supported, configured as stated in the configuration (reuse ctrl endpoint attribute vis-à-vis additionalAddresses).

**Comment by aschamberger** [comment]
Regarding debugging: I'm setting the loglevel via an env variable for the container and set it via JVM Parameter. @see: https://github.com/aschamberger/hassio-addons/blob/bbee72a87a91980792655d49fa5e134cfee4fa85/calimero-server/run.sh#L39 and https://github.com/aschamberger/hassio-addons/blob/bbee72a87a91980792655d49fa5e134cfee4fa85/calimero-server/run.sh#L89

**Comment by farmio** [comment]
Ah great, I'll look into that. 
I've moved to an x86 Linux host now (aarch64 Ubuntu on Mac VM wouldn't start Calimero Docker) and got a ConnectionResponse - so that's great!
When I try to send a TunnellingRequest it doesn't ACK - but it responds to the then following DisconnectRequest properly so that's something. Step by step. 

What is the difference between emulated and virtual subnets? I'd like to use the calimero container as unittest target for xknx so I don't need an actual subnet but proper ACSs and L_Data.con to test our connection logic.

**Comment by aschamberger** [comment]
Here both home-assistant.log and tcpdump at the same time. This is from a HA restart with routing configured and HA config as below. I also tried to send manually KNX commands via knx.send to 1/1/1. This was not processed on the KNX side as this would have resulted in a 1/4/1 state response.
```
logger:
  default: warning
  logs:
    homeassistant.components.fritz: error
    fritzconnection: error    ## it seems this one is the problematic
    fritzprofiles: error    
    # For most debugging needs `xnx.log` and one of `xknx.knx` or `xknx.telegram` are a good choice.
    #xknx: debug  # sets the level of all loggers
    xknx.log: debug  # provides general information (connection, etc.)
    xknx.raw_socket: debug  # logs incoming UDP frames in raw hex format
    xknx.knx: debug  # logs incoming and outgoing KNX/IP frames at socket level
    xknx.telegram: debug  # logs telegrams before they are being processed at device level or sent to an interface
    #xknx.state_updater: debug  # provides information about the state updater

knx:
  individual_address: 1.1.105
  routing:
```
[home-assistant.log](https://github.com/calimero-project/calimero-server/files/7698607/home-assistant.log)
[tcpdump.out.log](https://github.com/calimero-project/calimero-server/files/7698608/tcpdump.out.log)
